# XXX this workflow is intended for development/testing purposes
# if pushed to a public repository (presumably github.com/gardener/cc-utils), this indicates
# this happened by accident

name: Test
on:
  push:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: test
        run: |
          echo 'printing $ACTIONS_ID_TOKEN_REQUEST_TOKEN  $ACTIONS_ID_TOKEN_REQUEST_URL'
          echo "printing $ACTIONS_ID_TOKEN_REQUEST_TOKEN  $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "printing github context"
          cat <<EOF >ctx.json
          ${{ toJSON(github) }}
          EOF

          cat ctx.json
          echo
          echo

          jq . ctx.json
      - name: auth
        uses: gardener/cc-utils/.github/actions/oci-auth@master
        with:
          oci-image-reference: europe-docker.pkg.dev/gardener-project/releases
          gh-token: ${{ secrets.GITHUB_TOKEN }}
