# XXX this workflow is intended for development/testing purposes
# if pushed to a public repository (presumably github.com/gardener/cc-utils), this indicates
# this happened by accident

name: Test
on:
  push:
  workflow_dispatch:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo 'printing $ACTIONS_ID_TOKEN_REQUEST_TOKEN  $ACTIONS_ID_TOKEN_REQUEST_URL'
          echo "printing $ACTIONS_ID_TOKEN_REQUEST_TOKEN  $ACTIONS_ID_TOKEN_REQUEST_URL"
          echo "printing github context"
          cat <<EOF >ctx.json
          ${{ toJSON(github) }}
          EOF

          cat ctx.json
          echo
          echo

          jq . ctx.json
